#!/usr/bin/env python3
"""Generator untuk 5 notebook ablation (RNN, GRU, LSTM, BiLSTM, Transformer)."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent


def cells_shared(model_title: str, model_key: str, feature_type: str):
    """Sel-sel umum: mount, config, load, dataset, split, train loop, plots."""
    feature_label = {
        'mfcc': 'MFCC',
        'chromagram': 'Chromagram',
        'mfcc_chroma': 'MFCC + Chroma'
    }.get(feature_type, feature_type.upper())
    
    return [
        {"cell_type": "markdown", "metadata": {}, "source": [
            f"# Ablation: **{model_title}** × **{feature_label}**\n",
            "\n",
            "Alur: konfigurasi → muat data → urutan per lagu → padding → pelatihan per instrumen → visualisasi.\n"
        ]},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
            "# Cell 1 — Mount Drive (Colab), impor library, dan konfigurasi global\n",
            "try:\n",
            "    from google.colab import drive\n",
            "    drive.mount('/content/drive')\n",
            "    print('Google Drive berhasil di-mount.')\n",
            "except ImportError:\n",
            "    print('Bukan lingkungan Colab: langkah mount dilewati.')\n",
            "\n",
            "import os\n",
            "import re\n",
            "import json\n",
            "import pickle\n",
            "from pathlib import Path\n",
            "from typing import List, Tuple, Dict, Any, Optional\n",
            "\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "import matplotlib.pyplot as plt\n",
            "import seaborn as sns\n",
            "\n",
            "import torch\n",
            "import torch.nn as nn\n",
            "from torch.utils.data import Dataset, DataLoader\n",
            "from torch.nn.utils.rnn import pad_sequence\n",
            "\n",
            "from sklearn.preprocessing import LabelEncoder\n",
            "from sklearn.metrics import confusion_matrix\n",
            "\n",
            "sns.set_theme(style='whitegrid')\n",
            "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
            "print(f'Device: {device}')\n",
            "print(f'PyTorch: {torch.__version__}')\n",
            "\n",
            "# --- Konfigurasi path (sesuai struktur Drive Anda) ---\n",
            "BASE_PATH = Path(r'/content/drive/My Drive/Kuliah/Tugas Akhir/Master Dataset')\n",
            "INSTRUMENT_FOLDERS = [\n",
            "    'piano', 'bass', 'guitar', 'vocals',\n",
            "    'guitar_piano', 'guitar_piano_bass', 'no_vocals'\n",
            "]\n",
            "FEATURE_TYPE = " + repr(feature_type) + "\n",
            "FEATURE_FILENAME = f'extracted_features_{FEATURE_TYPE}.csv'\n",
            "PKL_PATTERN = f'extracted_features_{FEATURE_TYPE}.pkl'\n",
            "\n",
            "ARTIST_COL = 'artist'\n",
            "TITLE_COL = 'title'\n",
            "TARGET_COL = 'roman_numeral'  # 24 kelas — sesuaikan jika kolom target Anda berbeda\n",
            "TIME_COL = 'start_time'\n",
            "\n",
            "RANDOM_SEED = 42\n",
            "torch.manual_seed(RANDOM_SEED)\n",
            "np.random.seed(RANDOM_SEED)\n",
            "\n",
            "BATCH_SIZE = 8\n",
            "EPOCHS = 100\n",
            "LEARNING_RATE = 1e-3\n",
            "HIDDEN_SIZE = 128\n",
            "NUM_LAYERS = 2\n",
            "DROPOUT = 0.3\n",
            "VAL_RATIO = 0.2\n",
            "\n",
            "MODEL_KEY = " + repr(model_key) + "\n",
            "OUT_DIR = Path('/content/drive/My Drive/Kuliah/Tugas Akhir/ablation_outputs') / f'{MODEL_KEY}_{FEATURE_TYPE}'\n",
            "OUT_DIR.mkdir(parents=True, exist_ok=True)\n",
            "print(f'BASE_PATH exists: {BASE_PATH.exists()} | {BASE_PATH}')\n",
            "print(f'Feature type: {FEATURE_TYPE} → {FEATURE_FILENAME}')\n",
            "print(f'Output: {OUT_DIR}')\n"
        ]},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
            "# Cell 2 — Muat .pkl / fallback CSV, bentuk track_id = artist-title (on-the-fly)\n",
            "\n",
            "def sanitize_segment(s: str) -> str:\n",
            "    s = str(s).strip()\n",
            "    s = re.sub(r'\\s+', '_', s)\n",
            "    return s\n",
            "\n",
            "\n",
            "def add_track_id(df: pd.DataFrame) -> pd.DataFrame:\n",
            "    \"\"\"Gabung artist + title menjadi track_id unik per lagu (contoh: Vierratale-Seandainya).\"\"\"\n",
            "    out = df.copy()\n",
            "    out['track_id'] = (\n",
            "        out[ARTIST_COL].map(sanitize_segment).astype(str)\n",
            "        + '-'\n",
            "        + out[TITLE_COL].map(sanitize_segment).astype(str)\n",
            "    )\n",
            "    return out\n",
            "\n",
            "\n",
            "def find_tabular_file(folder: Path) -> Optional[Path]:\n",
            "    pkl_files = sorted(folder.glob(PKL_PATTERN))\n",
            "    if pkl_files:\n",
            "        return pkl_files[0]\n",
            "    csv_path = folder / CSV_FALLBACK\n",
            "    if csv_path.exists():\n",
            "        return csv_path\n",
            "    return None\n",
            "\n",
            "\n",
            "def load_tabular(path: Path) -> pd.DataFrame:\n",
            "    \"\"\"Memuat DataFrame dari .pkl atau .csv.\"\"\"\n",
            "    if path.suffix.lower() == '.pkl':\n",
            "        with open(path, 'rb') as f:\n",
            "            obj = pickle.load(f)\n",
            "        if not isinstance(obj, pd.DataFrame):\n",
            "            raise TypeError(f'Isi pkl harus DataFrame, dapat: {type(obj)}')\n",
            "        return obj.copy()\n",
            "    return pd.read_csv(path)\n",
            "\n",
            "\n",
            "def infer_feature_columns(df: pd.DataFrame) -> List[str]:\n",
            "    meta = {\n",
            "        ARTIST_COL, TITLE_COL, TARGET_COL, TIME_COL,\n",
            "        'track_id', 'part_song', 'roman_numeral', 'end_time', 'chord', 'label'\n",
            "    }\n",
            "    meta = meta & set(df.columns)\n",
            "    num_cols = []\n",
            "    for c in df.columns:\n",
            "        if c in meta or c == 'track_id':\n",
            "            continue\n",
            "        if pd.api.types.is_numeric_dtype(df[c]):\n",
            "            num_cols.append(c)\n",
            "    if not num_cols:\n",
            "        raise ValueError('Tidak ada kolom numerik fitur. Periksa nama kolom.')\n",
            "    return num_cols\n",
            "\n",
            "\n",
            "# Contoh: periksa folder pertama yang ada\n",
            "_demo_folder = None\n",
            "_f = None\n",
            "for name in INSTRUMENT_FOLDERS:\n",
            "    p = BASE_PATH / name\n",
            "    if p.is_dir():\n",
            "        _demo_folder = p\n",
            "        break\n",
            "if _demo_folder is None:\n",
            "    print('Peringatan: BASE_PATH belum berisi subfolder instrumen. Sesuaikan BASE_PATH.')\n",
            "else:\n",
            "    _f = find_tabular_file(_demo_folder)\n",
            "    print('Folder demo:', _demo_folder, '| file:', _f)\n",
            "    if _f is not None:\n",
            "        _df0 = load_tabular(_f)\n",
            "        _df0 = add_track_id(_df0)\n",
            "        print('Shape:', _df0.shape)\n",
            "        print('Kolom (10 pertama):', list(_df0.columns[:10]))\n",
            "        print('track_id contoh:', _df0['track_id'].iloc[0])\n",
            "    else:\n",
            "        print('Tidak ada .pkl atau CSV fallback di folder demo.')\n"
        ]},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
            "# Cell 3 — Group by track_id → list urutan; encoding label; tensor 3D + padding\n",
            "\n",
            "def prepare_dataframe(df: pd.DataFrame) -> Tuple[pd.DataFrame, LabelEncoder, List[str]]:\n",
            "    \"\"\"Menambahkan track_id, meng-encode label kord, mengurutkan per waktu.\"\"\"\n",
            "    df = add_track_id(df)\n",
            "    if TARGET_COL not in df.columns:\n",
            "        raise KeyError(f'Kolom target `{TARGET_COL}` tidak ada. Kolom: {list(df.columns)}')\n",
            "    if TIME_COL in df.columns:\n",
            "        df = df.sort_values([TIME_COL])\n",
            "    le = LabelEncoder()\n",
            "    df = df.copy()\n",
            "    df['label_idx'] = le.fit_transform(df[TARGET_COL].astype(str))\n",
            "    feat_cols = infer_feature_columns(df)\n",
            "    return df, le, feat_cols\n",
            "\n",
            "\n",
            "def dataframe_to_sequence_lists(\n",
            "    df: pd.DataFrame, feat_cols: List[str]\n",
            ") -> Tuple[List[np.ndarray], List[np.ndarray], List[str]]:\n",
            "    \"\"\"\n",
            "    Mengubah tabel 2D menjadi list sequence per lagu:\n",
            "    setiap elemen berbentuk (T_i, F) dan label (T_i,).\n",
            "    Ini ekuivalen dengan 'group by track_id' (tanpa sliding window).\n",
            "    Sliding window dapat ditambahkan dengan memotong setiap lagu menjadi segmen panjang tetap.\n",
            "    \"\"\"\n",
            "    seq_X: List[np.ndarray] = []\n",
            "    seq_y: List[np.ndarray] = []\n",
            "    track_order: List[str] = []\n",
            "    for tid, g in df.groupby('track_id', sort=False):\n",
            "        g = g.sort_values(TIME_COL) if TIME_COL in g.columns else g\n",
            "        X = g[feat_cols].values.astype(np.float32)\n",
            "        y = g['label_idx'].values.astype(np.int64)\n",
            "        if len(X) == 0:\n",
            "            continue\n",
            "        seq_X.append(X)\n",
            "        seq_y.append(y)\n",
            "        track_order.append(tid)\n",
            "    return seq_X, seq_y, track_order\n",
            "\n",
            "\n",
            "def dataframe_to_sliding_windows(\n",
            "    df: pd.DataFrame,\n",
            "    feat_cols: List[str],\n",
            "    window_size: int,\n",
            "    stride: int,\n",
            ") -> Tuple[List[np.ndarray], List[np.ndarray], List[str]]:\n",
            "    \"\"\"\n",
            "    Alternatif sliding window: tiap lagu dipotong menjadi segmen (T=window_size).\n",
            "    Ganti pemanggilan `dataframe_to_sequence_lists` dengan fungsi ini jika ingin jendela tetap.\n",
            "    \"\"\"\n",
            "    seq_X: List[np.ndarray] = []\n",
            "    seq_y: List[np.ndarray] = []\n",
            "    seg_ids: List[str] = []\n",
            "    for tid, g in df.groupby('track_id', sort=False):\n",
            "        g = g.sort_values(TIME_COL) if TIME_COL in g.columns else g\n",
            "        X = g[feat_cols].values.astype(np.float32)\n",
            "        y = g['label_idx'].values.astype(np.int64)\n",
            "        if len(X) < window_size:\n",
            "            continue\n",
            "        for start in range(0, len(X) - window_size + 1, stride):\n",
            "            seq_X.append(X[start : start + window_size])\n",
            "            seq_y.append(y[start : start + window_size])\n",
            "            seg_ids.append(f'{tid}#{start}')\n",
            "    return seq_X, seq_y, seg_ids\n",
            "\n",
            "\n",
            "class ChordSequenceDataset(Dataset):\n",
            "    \"\"\"Satu item = satu lagu (tensor 2D fitur + vektor label).\"\"\"\n",
            "\n",
            "    def __init__(self, seq_X: List[np.ndarray], seq_y: List[np.ndarray]):\n",
            "        self.seq_X = [torch.from_numpy(x) for x in seq_X]\n",
            "        self.seq_y = [torch.from_numpy(y) for y in seq_y]\n",
            "\n",
            "    def __len__(self):\n",
            "        return len(self.seq_X)\n",
            "\n",
            "    def __getitem__(self, idx: int):\n",
            "        return self.seq_X[idx], self.seq_y[idx]\n",
            "\n",
            "\n",
            "def collate_pad(batch):\n",
            "    \"\"\"\n",
            "    Padding variabel panjang → bentuk (batch, T_max, F) dan label (batch, T_max) dengan -100 di padding.\n",
            "    CrossEntropyLoss memakai ignore_index=-100 agar padding tidak dihitung.\n",
            "    \"\"\"\n",
            "    xs, ys = zip(*batch)\n",
            "    lengths = torch.tensor([x.size(0) for x in xs], dtype=torch.long)\n",
            "    x_pad = pad_sequence(xs, batch_first=True, padding_value=0.0)\n",
            "    y_pad = pad_sequence(ys, batch_first=True, padding_value=-100)\n",
            "    return x_pad, y_pad, lengths\n",
            "\n",
            "\n",
            "if _demo_folder is not None and _f is not None:\n",
            "    _dfp, _le, _fc = prepare_dataframe(_df0)\n",
            "    _sx, _sy, _tr = dataframe_to_sequence_lists(_dfp, _fc)\n",
            "    print('Jumlah lagu (sequence):', len(_sx))\n",
            "    print('Jumlah kelas:', len(_le.classes_))\n",
            "    print('Dim fitur F:', len(_fc))\n",
            "    print('Contoh panjang urutan:', _sx[0].shape if _sx else None)\n"
        ]},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
            "# Cell 4 — Split train/val berdasarkan track (hindari kebocoran irisan antar split)\n",
            "\n",
            "def split_sequences_by_track(\n",
            "    seq_X: List[np.ndarray],\n",
            "    seq_y: List[np.ndarray],\n",
            "    val_ratio: float = VAL_RATIO,\n",
            "    seed: int = RANDOM_SEED,\n",
            "):\n",
            "    n = len(seq_X)\n",
            "    idx = np.arange(n)\n",
            "    rng = np.random.RandomState(seed)\n",
            "    rng.shuffle(idx)\n",
            "    n_val = max(1, int(round(val_ratio * n))) if n > 1 else 1\n",
            "    val_idx = set(idx[:n_val])\n",
            "    tr_X, tr_y = [], []\n",
            "    va_X, va_y = [], []\n",
            "    for i in range(n):\n",
            "        if i in val_idx:\n",
            "            va_X.append(seq_X[i])\n",
            "            va_y.append(seq_y[i])\n",
            "        else:\n",
            "            tr_X.append(seq_X[i])\n",
            "            tr_y.append(seq_y[i])\n",
            "    if not tr_X:\n",
            "        tr_X, tr_y = va_X[:-1], va_y[:-1]\n",
            "        va_X, va_y = va_X[-1:], va_y[-1:]\n",
            "    return tr_X, tr_y, va_X, va_y\n",
            "\n",
            "\n",
            "def masked_accuracy(logits: torch.Tensor, targets: torch.Tensor) -> float:\n",
            "    \"\"\"Akurasi hanya pada timestep bukan padding (target != -100).\"\"\"\n",
            "    pred = logits.argmax(dim=-1)\n",
            "    mask = targets != -100\n",
            "    if mask.sum() == 0:\n",
            "        return 0.0\n",
            "    return (pred[mask] == targets[mask]).float().mean().item()\n",
            "\n",
            "\n",
            "print('Fungsi split_sequences_by_track dan masked_accuracy siap.')\n"
        ]},
    ]


def model_cell_rnn():
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "# Cell 5 — Model: Vanilla RNN\n",
        "# Keluaran logits berbentuk (batch, timesteps, num_classes) agar selaras dengan label per-frame.\n",
        "\n",
        "class ChordRNN(nn.Module):\n",
        "    def __init__(self, n_features: int, n_classes: int, hidden: int = HIDDEN_SIZE,\n",
        "                 num_layers: int = NUM_LAYERS, dropout: float = DROPOUT):\n",
        "        super().__init__()\n",
        "        self.rnn = nn.RNN(\n",
        "            n_features, hidden, num_layers=num_layers,\n",
        "            batch_first=True, dropout=dropout if num_layers > 1 else 0.0,\n",
        "            nonlinearity='tanh',\n",
        "        )\n",
        "        self.dropout = nn.Dropout(dropout)\n",
        "        self.fc = nn.Linear(hidden, n_classes)\n",
        "\n",
        "    def forward(self, x: torch.Tensor, lengths: Optional[torch.Tensor] = None) -> torch.Tensor:\n",
        "        # x: (B, T, F) — panjang sebenarnya bisa dipakai dengan pack, di sini cukup forward penuh lalu mask di loss\n",
        "        h, _ = self.rnn(x)\n",
        "        h = self.dropout(h)\n",
        "        return self.fc(h)\n",
        "\n",
        "\n",
        "def build_model(n_features: int, n_classes: int) -> nn.Module:\n",
        "    return ChordRNN(n_features, n_classes).to(device)\n",
        "\n",
        "\n",
        "_nf, _nc = 16, 24\n",
        "_m = build_model(_nf, _nc)\n",
        "_xb = torch.randn(2, 5, _nf).to(device)\n",
        "_lb = torch.tensor([5, 5])\n",
        "_out = _m(_xb, _lb)\n",
        "print('RNN logits shape:', _out.shape, '(diharapkan [2, 5, 24])')\n"
    ]}


def model_cell_gru():
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "# Cell 5 — Model: GRU\n",
        "\n",
        "class ChordGRU(nn.Module):\n",
        "    def __init__(self, n_features: int, n_classes: int, hidden: int = HIDDEN_SIZE,\n",
        "                 num_layers: int = NUM_LAYERS, dropout: float = DROPOUT):\n",
        "        super().__init__()\n",
        "        self.gru = nn.GRU(\n",
        "            n_features, hidden, num_layers=num_layers,\n",
        "            batch_first=True, dropout=dropout if num_layers > 1 else 0.0,\n",
        "        )\n",
        "        self.dropout = nn.Dropout(dropout)\n",
        "        self.fc = nn.Linear(hidden, n_classes)\n",
        "\n",
        "    def forward(self, x: torch.Tensor, lengths: Optional[torch.Tensor] = None) -> torch.Tensor:\n",
        "        h, _ = self.gru(x)\n",
        "        h = self.dropout(h)\n",
        "        return self.fc(h)\n",
        "\n",
        "\n",
        "def build_model(n_features: int, n_classes: int) -> nn.Module:\n",
        "    return ChordGRU(n_features, n_classes).to(device)\n",
        "\n",
        "\n",
        "_nf, _nc = 16, 24\n",
        "_m = build_model(_nf, _nc)\n",
        "_xb = torch.randn(2, 5, _nf).to(device)\n",
        "_out = _m(_xb)\n",
        "print('GRU logits shape:', _out.shape)\n"
    ]}


def model_cell_lstm():
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "# Cell 5 — Model: LSTM standar\n",
        "\n",
        "class ChordLSTM(nn.Module):\n",
        "    def __init__(self, n_features: int, n_classes: int, hidden: int = HIDDEN_SIZE,\n",
        "                 num_layers: int = NUM_LAYERS, dropout: float = DROPOUT):\n",
        "        super().__init__()\n",
        "        self.lstm = nn.LSTM(\n",
        "            n_features, hidden, num_layers=num_layers,\n",
        "            batch_first=True, dropout=dropout if num_layers > 1 else 0.0,\n",
        "        )\n",
        "        self.dropout = nn.Dropout(dropout)\n",
        "        self.fc = nn.Linear(hidden, n_classes)\n",
        "\n",
        "    def forward(self, x: torch.Tensor, lengths: Optional[torch.Tensor] = None) -> torch.Tensor:\n",
        "        h, _ = self.lstm(x)\n",
        "        h = self.dropout(h)\n",
        "        return self.fc(h)\n",
        "\n",
        "\n",
        "def build_model(n_features: int, n_classes: int) -> nn.Module:\n",
        "    return ChordLSTM(n_features, n_classes).to(device)\n",
        "\n",
        "\n",
        "_nf, _nc = 16, 24\n",
        "_m = build_model(_nf, _nc)\n",
        "_xb = torch.randn(2, 5, _nf).to(device)\n",
        "print('LSTM logits shape:', _m(_xb).shape)\n"
    ]}


def model_cell_bilstm():
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "# Cell 5 — Model: Bi-LSTM (keluaran gabungan dua arah → proyeksi ke kelas)\n",
        "\n",
        "class ChordBiLSTM(nn.Module):\n",
        "    def __init__(self, n_features: int, n_classes: int, hidden: int = HIDDEN_SIZE,\n",
        "                 num_layers: int = NUM_LAYERS, dropout: float = DROPOUT):\n",
        "        super().__init__()\n",
        "        self.lstm = nn.LSTM(\n",
        "            n_features, hidden, num_layers=num_layers,\n",
        "            batch_first=True, bidirectional=True,\n",
        "            dropout=dropout if num_layers > 1 else 0.0,\n",
        "        )\n",
        "        self.dropout = nn.Dropout(dropout)\n",
        "        self.fc = nn.Linear(hidden * 2, n_classes)\n",
        "\n",
        "    def forward(self, x: torch.Tensor, lengths: Optional[torch.Tensor] = None) -> torch.Tensor:\n",
        "        h, _ = self.lstm(x)\n",
        "        h = self.dropout(h)\n",
        "        return self.fc(h)\n",
        "\n",
        "\n",
        "def build_model(n_features: int, n_classes: int) -> nn.Module:\n",
        "    return ChordBiLSTM(n_features, n_classes).to(device)\n",
        "\n",
        "\n",
        "_nf, _nc = 16, 24\n",
        "_m = build_model(_nf, _nc)\n",
        "print('BiLSTM logits shape:', _m(torch.randn(2, 5, _nf).to(device)).shape)\n"
    ]}


def model_cell_transformer():
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "# Cell 5 — Model: Transformer Encoder ringkas (1–2 lapis) + proyeksi input\n",
        "import math\n",
        "\n",
        "class PositionalEncoding(nn.Module):\n",
        "    \"\"\"Penambahan posisi sinusoidal untuk urutan waktu (batch, T, d_model).\"\"\"\n",
        "\n",
        "    def __init__(self, d_model: int, max_len: int = 5000, dropout: float = 0.1):\n",
        "        super().__init__()\n",
        "        self.dropout = nn.Dropout(dropout)\n",
        "        pe = torch.zeros(max_len, d_model)\n",
        "        pos = torch.arange(0, max_len, dtype=torch.float32).unsqueeze(1)\n",
        "        div = torch.exp(torch.arange(0, d_model, 2, dtype=torch.float32) * (-math.log(10000.0) / d_model))\n",
        "        pe[:, 0::2] = torch.sin(pos * div)\n",
        "        pe[:, 1::2] = torch.cos(pos * div)\n",
        "        self.register_buffer('pe', pe.unsqueeze(0))\n",
        "\n",
        "    def forward(self, x: torch.Tensor) -> torch.Tensor:\n",
        "        # x: (B, T, d_model)\n",
        "        T = x.size(1)\n",
        "        x = x + self.pe[:, :T, :]\n",
        "        return self.dropout(x)\n",
        "\n",
        "\n",
        "class ChordTransformerEncoder(nn.Module):\n",
        "    def __init__(\n",
        "        self,\n",
        "        n_features: int,\n",
        "        n_classes: int,\n",
        "        d_model: int = 128,\n",
        "        nhead: int = 4,\n",
        "        num_layers: int = 2,\n",
        "        dim_ff: int = 256,\n",
        "        dropout: float = DROPOUT,\n",
        "    ):\n",
        "        super().__init__()\n",
        "        self.input_proj = nn.Linear(n_features, d_model)\n",
        "        self.pos = PositionalEncoding(d_model, dropout=dropout)\n",
        "        enc_layer = nn.TransformerEncoderLayer(\n",
        "            d_model=d_model, nhead=nhead, dim_feedforward=dim_ff,\n",
        "            dropout=dropout, batch_first=True, activation='gelu',\n",
        "        )\n",
        "        self.encoder = nn.TransformerEncoder(enc_layer, num_layers=num_layers)\n",
        "        self.fc = nn.Linear(d_model, n_classes)\n",
        "\n",
        "    def forward(self, x: torch.Tensor, lengths: Optional[torch.Tensor] = None) -> torch.Tensor:\n",
        "        # Padding mask: True di posisi padding (Transformer PyTorch)\n",
        "        B, T, _ = x.shape\n",
        "        z = self.input_proj(x)\n",
        "        z = self.pos(z)\n",
        "        if lengths is not None:\n",
        "            rng = torch.arange(T, device=x.device).unsqueeze(0).expand(B, T)\n",
        "            pad_mask = rng >= lengths.to(x.device).unsqueeze(1)\n",
        "        else:\n",
        "            pad_mask = None\n",
        "        z = self.encoder(z, src_key_padding_mask=pad_mask)\n",
        "        return self.fc(z)\n",
        "\n",
        "\n",
        "def build_model(n_features: int, n_classes: int) -> nn.Module:\n",
        "    return ChordTransformerEncoder(n_features, n_classes).to(device)\n",
        "\n",
        "\n",
        "_nf, _nc = 16, 24\n",
        "_m = build_model(_nf, _nc)\n",
        "_xb = torch.randn(2, 5, _nf).to(device)\n",
        "_lb = torch.tensor([5, 5])\n",
        "print('Transformer logits shape:', _m(_xb, _lb).shape)\n"
    ]}


def training_cells():
    return [
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
            "# Cell 6 — Satu epoch & pelatihan per folder instrumen\n",
            "\n",
            "def train_one_epoch(model, loader, optimizer, criterion):\n",
            "    model.train()\n",
            "    total_loss = 0.0\n",
            "    total_acc = 0.0\n",
            "    n_batches = 0\n",
            "    for xb, yb, lens in loader:\n",
            "        xb = xb.to(device)\n",
            "        yb = yb.to(device)\n",
            "        lens = lens.to(device)\n",
            "        optimizer.zero_grad()\n",
            "        logits = model(xb, lens)\n",
            "        loss = criterion(logits.view(-1, logits.size(-1)), yb.view(-1))\n",
            "        loss.backward()\n",
            "        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)\n",
            "        optimizer.step()\n",
            "        total_loss += loss.item()\n",
            "        total_acc += masked_accuracy(logits, yb)\n",
            "        n_batches += 1\n",
            "    return total_loss / max(n_batches, 1), total_acc / max(n_batches, 1)\n",
            "\n",
            "\n",
            "@torch.no_grad()\n",
            "def evaluate(model, loader, criterion):\n",
            "    model.eval()\n",
            "    total_loss = 0.0\n",
            "    total_acc = 0.0\n",
            "    n_batches = 0\n",
            "    for xb, yb, lens in loader:\n",
            "        xb = xb.to(device)\n",
            "        yb = yb.to(device)\n",
            "        lens = lens.to(device)\n",
            "        logits = model(xb, lens)\n",
            "        loss = criterion(logits.view(-1, logits.size(-1)), yb.view(-1))\n",
            "        total_loss += loss.item()\n",
            "        total_acc += masked_accuracy(logits, yb)\n",
            "        n_batches += 1\n",
            "    return total_loss / max(n_batches, 1), total_acc / max(n_batches, 1)\n",
            "\n",
            "\n",
            "def run_training_for_instrument(\n",
            "    instrument_name: str,\n",
            "    df: pd.DataFrame,\n",
            "    le: LabelEncoder,\n",
            "    feat_cols: List[str],\n",
            ") -> Dict[str, Any]:\n",
            "    seq_X, seq_y, _ = dataframe_to_sequence_lists(df, feat_cols)\n",
            "    if len(seq_X) < 2:\n",
            "        print(f'  [{instrument_name}] Data kurang: hanya {len(seq_X)} lagu. Skip.')\n",
            "        return {'instrument': instrument_name, 'skipped': True}\n",
            "    tr_X, tr_y, va_X, va_y = split_sequences_by_track(seq_X, seq_y)\n",
            "    n_classes = len(le.classes_)\n",
            "    n_features = len(feat_cols)\n",
            "\n",
            "    train_ds = ChordSequenceDataset(tr_X, tr_y)\n",
            "    val_ds = ChordSequenceDataset(va_X, va_y)\n",
            "    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, collate_fn=collate_pad)\n",
            "    val_loader = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False, collate_fn=collate_pad)\n",
            "\n",
            "    model = build_model(n_features, n_classes)\n",
            "    optimizer = torch.optim.AdamW(model.parameters(), lr=LEARNING_RATE)\n",
            "    criterion = nn.CrossEntropyLoss(ignore_index=-100)\n",
            "\n",
            "    history = {'train_loss': [], 'train_acc': [], 'val_loss': [], 'val_acc': []}\n",
            "    best_val = -1.0\n",
            "    best_state = None\n",
            "\n",
            "    for epoch in range(1, EPOCHS + 1):\n",
            "        tr_loss, tr_acc = train_one_epoch(model, train_loader, optimizer, criterion)\n",
            "        va_loss, va_acc = evaluate(model, val_loader, criterion)\n",
            "        history['train_loss'].append(tr_loss)\n",
            "        history['train_acc'].append(tr_acc)\n",
            "        history['val_loss'].append(va_loss)\n",
            "        history['val_acc'].append(va_acc)\n",
            "        print(f'  Ep {epoch:02d}/{EPOCHS} | tr_loss={tr_loss:.4f} tr_acc={tr_acc:.4f} | va_loss={va_loss:.4f} va_acc={va_acc:.4f}')\n",
            "        if va_acc > best_val:\n",
            "            best_val = va_acc\n",
            "            best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}\n",
            "\n",
            "    ckpt_path = OUT_DIR / f'best_{instrument_name}.pt'\n",
            "    if best_state is not None:\n",
            "        torch.save({'model': best_state, 'classes': le.classes_.tolist(), 'feat_cols': feat_cols}, ckpt_path)\n",
            "    return {\n",
            "        'instrument': instrument_name,\n",
            "        'skipped': False,\n",
            "        'best_val_acc': float(best_val),\n",
            "        'history': history,\n",
            "        'checkpoint': str(ckpt_path),\n",
            "        'label_encoder_classes': le.classes_.tolist(),\n",
            "    }\n",
            "\n",
            "\n",
            "print('Pipeline pelatihan (train_one_epoch / evaluate / run_training_for_instrument) siap.')\n"
        ]},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
            "# Cell 7 — Iterasi semua folder instrumen untuk model ini (satu arsitektur per notebook)\n",
            "\n",
            "def load_instrument_dataframe(folder_name: str) -> Optional[Tuple[pd.DataFrame, LabelEncoder, List[str]]]:\n",
            "    folder = BASE_PATH / folder_name\n",
            "    if not folder.is_dir():\n",
            "        print(f'[skip] Folder tidak ada: {folder}')\n",
            "        return None\n",
            "    fp = find_tabular_file(folder)\n",
            "    if fp is None:\n",
            "        print(f'[skip] Tidak ada file tabular di: {folder}')\n",
            "        return None\n",
            "    raw = load_tabular(fp)\n",
            "    df, le, feat_cols = prepare_dataframe(raw)\n",
            "    return df, le, feat_cols\n",
            "\n",
            "\n",
            "all_results: List[Dict[str, Any]] = []\n",
            "for inst in INSTRUMENT_FOLDERS:\n",
            "    print(f'=== Instrumen: {inst} | Model: {MODEL_KEY} × Feature: {FEATURE_TYPE} ===')\n",
            "    packed = load_instrument_dataframe(inst)\n",
            "    if packed is None:\n",
            "        continue\n",
            "    df_i, le_i, fc_i = packed\n",
            "    res = run_training_for_instrument(inst, df_i, le_i, fc_i)\n",
            "    res['model'] = MODEL_KEY\n",
            "    res['feature_type'] = FEATURE_TYPE\n",
            "    all_results.append(res)\n",
            "\n",
            "summary_path = OUT_DIR / 'summary_all_instruments.json'\n",
            "with open(summary_path, 'w', encoding='utf-8') as f:\n",
            "    json.dump(all_results, f, ensure_ascii=False, indent=2, default=str)\n",
            "print('Ringkasan disimpan:', summary_path)\n",
            "print('Jumlah run:', len(all_results))\n"
        ]},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
            "# Cell 8 — Visualisasi: bar chart akurasi validasi terbaik per instrumen (model = notebook ini)\n",
            "\n",
            "rows = []\n",
            "for r in all_results:\n",
            "    if r.get('skipped'):\n",
            "        continue\n",
            "    rows.append({'instrument': r['instrument'], 'model': r['model'], 'val_acc': r['best_val_acc']})\n",
            "\n",
            "if not rows:\n",
            "    print('Belum ada hasil untuk diplot (periksa path data atau isi folder).')\n",
            "else:\n",
            "    plot_df = pd.DataFrame(rows)\n",
            "    inst_order = [x for x in INSTRUMENT_FOLDERS if x in plot_df['instrument'].values]\n",
            "    plt.figure(figsize=(10, 5))\n",
            "    sns.barplot(data=plot_df, x='instrument', y='val_acc', order=inst_order, hue='model', dodge=False)\n",
            "    plt.ylabel('Akurasi validasi (terbaik)')\n",
            "    plt.xlabel('Instrumen / skenario')\n",
            "    plt.title(f'Perbandingan akurasi — model: {MODEL_KEY}')\n",
            "    plt.xticks(rotation=25, ha='right')\n",
            "    plt.tight_layout()\n",
            "    plt.savefig(OUT_DIR / f'bar_val_acc_{MODEL_KEY}.png', dpi=150)\n",
            "    plt.show()\n",
            "    print(plot_df)\n"
        ]},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
            "# Cell 9 — Confusion matrix pada checkpoint terbaik (instrumen dengan val_acc tertinggi)\n",
            "\n",
            "@torch.no_grad()\n",
            "def collect_predictions(model, loader, n_classes: int):\n",
            "    model.eval()\n",
            "    all_p = []\n",
            "    all_t = []\n",
            "    for xb, yb, lens in loader:\n",
            "        xb = xb.to(device)\n",
            "        yb = yb.to(device)\n",
            "        lens = lens.to(device)\n",
            "        logits = model(xb, lens)\n",
            "        pred = logits.argmax(dim=-1)\n",
            "        mask = yb != -100\n",
            "        all_p.append(pred[mask].cpu().numpy())\n",
            "        all_t.append(yb[mask].cpu().numpy())\n",
            "    if not all_p:\n",
            "        return np.array([]), np.array([])\n",
            "    return np.concatenate(all_p), np.concatenate(all_t)\n",
            "\n",
            "\n",
            "valid_runs = [r for r in all_results if not r.get('skipped') and r.get('best_val_acc') is not None]\n",
            "if not valid_runs:\n",
            "    print('Tidak ada model terlatih untuk confusion matrix.')\n",
            "else:\n",
            "    best_run = max(valid_runs, key=lambda x: x['best_val_acc'])\n",
            "    inst = best_run['instrument']\n",
            "    print('Instrumen terbaik (val_acc):', inst, '| acc:', best_run['best_val_acc'])\n",
            "    packed = load_instrument_dataframe(inst)\n",
            "    if packed is None:\n",
            "        print('Gagal memuat data untuk evaluasi.')\n",
            "    else:\n",
            "        df_e, le_e, feat_e = packed\n",
            "        seq_X, seq_y, _ = dataframe_to_sequence_lists(df_e, feat_e)\n",
            "        tr_X, tr_y, va_X, va_y = split_sequences_by_track(seq_X, seq_y)\n",
            "        val_ds = ChordSequenceDataset(va_X, va_y)\n",
            "        val_loader = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False, collate_fn=collate_pad)\n",
            "        n_classes = len(le_e.classes_)\n",
            "        n_features = len(feat_e)\n",
            "        model = build_model(n_features, n_classes)\n",
            "        ckpt = torch.load(best_run['checkpoint'], map_location=device, weights_only=False)\n",
            "        model.load_state_dict(ckpt['model'])\n",
            "        model.to(device)\n",
            "        y_pred, y_true = collect_predictions(model, val_loader, n_classes)\n",
            "        if y_true.size == 0:\n",
            "            print('Tidak ada contoh validasi.')\n",
            "        else:\n",
            "            cm = confusion_matrix(y_true, y_pred, labels=np.arange(n_classes))\n",
            "            plt.figure(figsize=(12, 10))\n",
            "            sns.heatmap(cm, annot=False, fmt='d', cmap='Blues',\n",
            "                        xticklabels=le_e.classes_, yticklabels=le_e.classes_)\n",
            "            plt.xlabel('Prediksi')\n",
            "            plt.ylabel('Sebenarnya')\n",
            "            plt.title(f'Confusion matrix — {MODEL_KEY} | {inst}')\n",
            "            plt.tight_layout()\n",
            "            plt.savefig(OUT_DIR / f'cm_best_{MODEL_KEY}.png', dpi=150)\n",
            "            plt.show()\n",
            "            print('Ukuran matriks:', cm.shape)\n"
        ]},
    ]


def aggregation_cell():
    """Bar chart agregat: bandingkan models × feature types."""
    return [
        {"cell_type": "markdown", "metadata": {}, "source": [
            "### Agregasi multi-model & feature type\n",
            "\n",
            "Jalankan sel berikut setelah semua notebook dijalankan.\n",
            "Grafik: **sumbu X = model**, **hue = feature type**, agregasi semua instrumen.\n"
        ]},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
            "# Cell 10 — Bar chart: Model vs Feature Type (agregasi semua instrumen)\n",
            "\n",
            "AGG_ROOT = OUT_DIR.parent.parent if 'feature_type' in dir() else OUT_DIR.parent\n",
            "MODEL_KEYS_ORDER = ['rnn', 'gru', 'lstm', 'bilstm', 'transformer']\n",
            "FEATURE_TYPES_ORDER = ['mfcc', 'chromagram', 'mfcc_chroma']\n",
            "MODEL_LABEL_MAP = {\n",
            "    'rnn': 'Vanilla RNN',\n",
            "    'gru': 'GRU',\n",
            "    'lstm': 'LSTM',\n",
            "    'bilstm': 'Bi-LSTM',\n",
            "    'transformer': 'Transformer',\n",
            "}\n",
            "FEATURE_LABEL_MAP = {\n",
            "    'mfcc': 'MFCC',\n",
            "    'chromagram': 'Chromagram',\n",
            "    'mfcc_chroma': 'MFCC + Chroma',\n",
            "}\n",
            "\n",
            "agg_rows = []\n",
            "for mk in MODEL_KEYS_ORDER:\n",
            "    for ft in FEATURE_TYPES_ORDER:\n",
            "        p = AGG_ROOT / f'{mk}_{ft}' / 'summary_all_instruments.json'\n",
            "        if not p.exists():\n",
            "            print(f'Belum ada: {p}')\n",
            "            continue\n",
            "        try:\n",
            "            with open(p, 'r', encoding='utf-8') as f:\n",
            "                data = json.load(f)\n",
            "            for r in data:\n",
            "                if r.get('skipped'):\n",
            "                    continue\n",
            "                agg_rows.append({\n",
            "                    'model': MODEL_LABEL_MAP.get(mk, mk),\n",
            "                    'model_key': mk,\n",
            "                    'feature': FEATURE_LABEL_MAP.get(ft, ft),\n",
            "                    'feature_key': ft,\n",
            "                    'instrument': r['instrument'],\n",
            "                    'val_acc': r['best_val_acc'],\n",
            "                })\n",
            "        except Exception as e:\n",
            "            print(f'Error loading {p}: {e}')\n",
            "            continue\n",
            "\n",
            "if not agg_rows:\n",
            "    print('Belum ada ringkasan agregat. Jalankan semua notebook terlebih dahulu.')\n",
            "else:\n",
            "    adf = pd.DataFrame(agg_rows)\n",
            "    \n",
            "    # 1. Perbandingan Model vs Feature Type (agregasi semua instrumen)\n",
            "    agg1 = adf.groupby(['model', 'feature'])['val_acc'].mean().reset_index()\n",
            "    agg1['model_f'] = pd.Categorical(agg1['model'], categories=[MODEL_LABEL_MAP[k] for k in MODEL_KEYS_ORDER], ordered=True)\n",
            "    plt.figure(figsize=(12, 6))\n",
            "    sns.barplot(data=agg1, x='model_f', y='val_acc', hue='feature')\n",
            "    plt.ylabel('Rata-rata Akurasi Validasi')\n",
            "    plt.xlabel('Model')\n",
            "    plt.title('Perbandingan Model × Feature Type (agregasi semua instrumen)')\n",
            "    plt.xticks(rotation=15, ha='right')\n",
            "    plt.legend(title='Feature Type', bbox_to_anchor=(1.05, 1), loc='upper left')\n",
            "    plt.tight_layout()\n",
            "    plt.savefig(AGG_ROOT / 'comparison_model_vs_feature.png', dpi=150, bbox_inches='tight')\n",
            "    plt.show()\n",
            "    print('\\n=== Agregasi Model vs Feature Type ===' )\n",
            "    print(agg1.pivot(index='model_f', columns='feature', values='val_acc'))\n",
            "    \n",
            "    # 2. Perbandingan Feature Type per Model (subset: ambil satu model)\n",
            "    if 'lstm' in adf['model_key'].values:\n",
            "        lstm_df = adf[adf['model_key'] == 'lstm']\n",
            "        inst_order = lstm_df['instrument'].unique()\n",
            "        plt.figure(figsize=(12, 6))\n",
            "        sns.barplot(data=lstm_df, x='instrument', y='val_acc', hue='feature', order=inst_order)\n",
            "        plt.ylabel('Akurasi Validasi')\n",
            "        plt.xlabel('Instrumen')\n",
            "        plt.title('LSTM: Perbandingan Feature Type per Instrumen')\n",
            "        plt.xticks(rotation=25, ha='right')\n",
            "        plt.legend(title='Feature Type', bbox_to_anchor=(1.05, 1), loc='upper left')\n",
            "        plt.tight_layout()\n",
            "        plt.savefig(AGG_ROOT / 'comparison_feature_by_instrument_lstm.png', dpi=150, bbox_inches='tight')\n",
            "        plt.show()\n",
            "    \n",
            "    print('\\nFile agregasi tersimpan di:', AGG_ROOT)\n"
        ]},
    ]


MODEL_SPECS = [
    ("Vanilla RNN", "rnn", model_cell_rnn),
    ("GRU", "gru", model_cell_gru),
    ("LSTM", "lstm", model_cell_lstm),
    ("Bi-LSTM", "bilstm", model_cell_bilstm),
    ("Transformer Encoder", "transformer", model_cell_transformer),
]


def build_notebook(title: str, key: str, model_fn, feature_type: str):
    cells = list(cells_shared(title, key, feature_type))
    cells.append(model_fn())
    cells.extend(training_cells())
    cells.extend(aggregation_cell())
    return {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "pygments_lexer": "ipython3"},
        },
        "cells": cells,
    }


def main():
    feature_types = ['mfcc', 'chromagram', 'mfcc_chroma']
    
    for title, key, model_fn in MODEL_SPECS:
        for ft in feature_types:
            nb = build_notebook(title, key, model_fn, ft)
            out = ROOT / f"ablation_{key}_{ft}.ipynb"
            with open(out, "w", encoding="utf-8") as f:
                json.dump(nb, f, ensure_ascii=False, indent=1)
            print(f"Wrote {out}")


if __name__ == "__main__":
    main()
