import json
from pathlib import Path

# --- CONFIGURATION FOR GENERATOR ---
# These variables control what kind of notebooks are generated
# The user can change these in the generated notebooks' first cell too.

def create_notebook(filename, cells):
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump({"cells": cells, "metadata": {}, "nbformat": 4, "nbformat_minor": 5}, f, indent=2)
    print(f"Generated: {filename}")

def get_base_config_cell(stage_name):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            f"# {stage_name} Base Configuration\n",
            "import os\n",
            "import re\n",
            "import json\n",
            "import pickle\n",
            "from pathlib import Path\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "import matplotlib.pyplot as plt\n",
            "import seaborn as sns\n",
            "plt.rcParams.update({'font.size': 18})\n",
            "plt.rcParams['axes.titlesize'] = 20\n",
            "plt.rcParams['axes.labelsize'] = 18\n",
            "plt.rcParams['xtick.labelsize'] = 16\n",
            "plt.rcParams['ytick.labelsize'] = 16\n",
            "plt.rcParams['legend.fontsize'] = 16\n",
            "import torch\n",
            "\n",
            "# --- GLOBAL PATHS ---\n",
            "BASE_PATH = Path('./input')\n",
            "PROCESSED_PATH = Path('./processed')\n",
            "OUTPUT_PATH = Path('./outputs')\n",
            "\n",
            "PROCESSED_PATH.mkdir(exist_ok=True)\n",
            "OUTPUT_PATH.mkdir(exist_ok=True)\n",
            "\n",
            "RANDOM_SEED = 42\n",
            "np.random.seed(RANDOM_SEED)\n",
            "torch.manual_seed(RANDOM_SEED)\n",
            "\n",
            "print(f'Stage: {stage_name}')\n",
            "print(f'Input Path: {BASE_PATH}')\n"
        ]
    }

def get_experiment_config_cell(stage_name):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            f"# {stage_name} Experiment Configuration\n",
            "import os\n",
            "import re\n",
            "import json\n",
            "import pickle\n",
            "from pathlib import Path\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "import matplotlib.pyplot as plt\n",
            "import seaborn as sns\n",
            "plt.rcParams.update({'font.size': 18})\n",
            "plt.rcParams['axes.titlesize'] = 20\n",
            "plt.rcParams['axes.labelsize'] = 18\n",
            "plt.rcParams['xtick.labelsize'] = 16\n",
            "plt.rcParams['ytick.labelsize'] = 16\n",
            "plt.rcParams['legend.fontsize'] = 16\n",
            "import torch\n",
            "\n",
            "# --- EXPERIMENT SETTINGS ---\n",
            "# Modes: 'FEATURE_COMPARISON', 'MODEL_COMPARISON', 'INSTRUMENT_COMPARISON'\n",
            "EXPERIMENT_MODE = 'FEATURE_COMPARISON'\n",
            "\n",
            "# Defaults (used when not being compared)\n",
            "FIXED_MODEL = 'lstm'\n",
            "FIXED_FEATURE = 'mfcc'\n",
            "FIXED_INSTRUMENT = 'raw_audio'\n",
            "\n",
            "# --- GLOBAL PATHS ---\n",
            "BASE_PATH = Path('./input')\n",
            "PROCESSED_PATH = Path('./processed')\n",
            "OUTPUT_PATH = Path('./outputs')\n",
            "\n",
            "# --- DYNAMIC LISTS FOR FILTERING ---\n",
            "if EXPERIMENT_MODE == 'FEATURE_COMPARISON':\n",
            "    MODELS_TO_TEST = [FIXED_MODEL]\n",
            "    FEATURES_TO_TEST = ['mfcc', 'chromagram', 'mfcc_chroma']\n",
            "    INSTRUMENTS_TO_TEST = [FIXED_INSTRUMENT]\n",
            "elif EXPERIMENT_MODE == 'MODEL_COMPARISON':\n",
            "    MODELS_TO_TEST = ['rnn', 'gru', 'lstm', 'bilstm', 'transformer']\n",
            "    FEATURES_TO_TEST = [FIXED_FEATURE]\n",
            "    INSTRUMENTS_TO_TEST = [FIXED_INSTRUMENT]\n",
            "elif EXPERIMENT_MODE == 'INSTRUMENT_COMPARISON':\n",
            "    MODELS_TO_TEST = [FIXED_MODEL]\n",
            "    FEATURES_TO_TEST = [FIXED_FEATURE]\n",
            "    INSTRUMENTS_TO_TEST = [\n",
            "        'bass', 'guitar', 'guitar_piano', 'guitar_piano_bass', \n",
            "        'no_vocals', 'piano', 'raw_audio', 'vocals'\n",
            "    ]\n",
            "\n",
            "RANDOM_SEED = 42\n",
            "np.random.seed(RANDOM_SEED)\n",
            "torch.manual_seed(RANDOM_SEED)\n",
            "\n",
            "print(f'Experiment Mode: {EXPERIMENT_MODE}')\n"
        ]
    }

# --- 01_EDA.ipynb ---
def gen_eda():
    cells = [
        {"cell_type": "markdown", "metadata": {}, "source": ["# 01. Exploratory Data Analysis\n", "Menganalisis distribusi fitur dan label sebelum preprocessing."]},
        get_base_config_cell("EDA"),
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def load_data(instrument, feature_type):\n",
                "    path_pkl = BASE_PATH / instrument / feature_type / f'extracted_features_{feature_type}.pkl'\n",
                "    path_csv = BASE_PATH / instrument / feature_type / f'extracted_features_{feature_type}.csv'\n",
                "    \n",
                "    if path_pkl.exists():\n",
                "        with open(path_pkl, 'rb') as f:\n",
                "            return pickle.load(f)\n",
                "    return pd.read_csv(path_csv)\n",
                "\n",
                "# Pick a sample for EDA (e.g., raw_audio/mfcc)\n",
                "df = load_data('raw_audio', 'mfcc')\n",
                "print(f'Loaded {len(df)} rows sample')\n",
                "df.head()"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Label Distribution\n",
                "plt.figure(figsize=(15, 5))\n",
                "sns.countplot(data=df, x='roman_numeral', order=df['roman_numeral'].value_counts().index)\n",
                "plt.title('Distribution of Roman Numeral Chords')\n",
                "plt.xticks(rotation=45)\n",
                "plt.show()"
            ]
        }
    ]
    create_notebook('01_eda.ipynb', cells)

# --- 02_PREPROCESSING.ipynb ---
def gen_preprocessing():
    cells = [
        {"cell_type": "markdown", "metadata": {}, "source": ["# 02. Preprocessing\n", "Cleaning, Normalization, Encoding, and Scaling for ALL data found in /input."]},
        get_base_config_cell("Preprocessing"),
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "from sklearn.preprocessing import LabelEncoder, StandardScaler\n",
                "\n",
                "def sanitize_name(s):\n",
                "    return re.sub(r'\\s+', '_', str(s).strip())\n",
                "\n",
                "def process_all_data():\n",
                "    all_processed = {}\n",
                "    all_labels = set()\n",
                "    \n",
                "    # 1. Find all instruments and features\n",
                "    instruments = [d.name for d in BASE_PATH.iterdir() if d.is_dir() and not d.name.startswith('.')]\n",
                "    print(f'Found instruments: {instruments}')\n",
                "    \n",
                "    # 2. Collect all possible labels first\n",
                "    for inst in instruments:\n",
                "        inst_path = BASE_PATH / inst\n",
                "        features = [d.name for d in inst_path.iterdir() if d.is_dir()]\n",
                "        for feat in features:\n",
                "            path_pkl = inst_path / feat / f'extracted_features_{feat}.pkl'\n",
                "            path_csv = inst_path / feat / f'extracted_features_{feat}.csv'\n",
                "            \n",
                "            if path_pkl.exists():\n",
                "                with open(path_pkl, 'rb') as f: df_temp = pickle.load(f)\n",
                "            elif path_csv.exists():\n",
                "                df_temp = pd.read_csv(path_csv)\n",
                "            else: continue\n",
                "            \n",
                "            all_labels.update(df_temp['roman_numeral'].unique())\n",
                "    \n",
                "    le = LabelEncoder()\n",
                "    le.fit(list(all_labels))\n",
                "    print(f'Total classes: {len(le.classes_)}')\n",
                "    \n",
                "    # 3. Process each combination\n",
                "    for inst in instruments:\n",
                "        inst_path = BASE_PATH / inst\n",
                "        features = [d.name for d in inst_path.iterdir() if d.is_dir()]\n",
                "        for feat in features:\n",
                "            path_pkl = inst_path / feat / f'extracted_features_{feat}.pkl'\n",
                "            path_csv = inst_path / feat / f'extracted_features_{feat}.csv'\n",
                "            \n",
                "            if path_pkl.exists():\n",
                "                with open(path_pkl, 'rb') as f: df = pickle.load(f)\n",
                "            elif path_csv.exists():\n",
                "                df = pd.read_csv(path_csv)\n",
                "            else: continue\n",
                "            \n",
                "            # Track ID\n",
                "            if 'track_id' not in df.columns:\n",
                "                df['track_id'] = df['artist'].map(sanitize_name) + '-' + df['title'].map(sanitize_name)\n",
                "            \n",
                "            # Features\n",
                "            feat_cols = [c for c in df.columns if c not in ['artist', 'title', 'start_time', 'end_time', 'roman_numeral', 'chord', 'label', 'track_id']]\n",
                "            \n",
                "            # Scaling\n",
                "            scaler = StandardScaler()\n",
                "            df[feat_cols] = scaler.fit_transform(df[feat_cols])\n",
                "            \n",
                "            # Encoding\n",
                "            df['label_idx'] = le.transform(df['roman_numeral'])\n",
                "            \n",
                "            # Group into sequences\n",
                "            sequences = []\n",
                "            for tid, group in df.groupby('track_id'):\n",
                "                group = group.sort_values('start_time')\n",
                "                X = group[feat_cols].values.astype(np.float32)\n",
                "                y = group['label_idx'].values.astype(np.int64)\n",
                "                sequences.append({'track_id': tid, 'X': X, 'y': y})\n",
                "            \n",
                "            key = f'{inst}_{feat}'\n",
                "            all_processed[key] = {\n",
                "                'sequences': sequences,\n",
                "                'feat_cols': feat_cols,\n",
                "                'classes': le.classes_.tolist()\n",
                "            }\n",
                "            print(f'Processed {key}: {len(sequences)} sequences')\n",
                "    \n",
                "    # Save Master File\n",
                "    out_file = PROCESSED_PATH / 'master_processed_data.pkl'\n",
                "    with open(out_file, 'wb') as f:\n",
                "        pickle.dump(all_processed, f)\n",
                "    print(f'\\nSaved MASTER processed data to {out_file}')\n",
                "\n",
                "process_all_data()"
            ]
        }
    ]
    create_notebook('02_preprocessing.ipynb', cells)

# --- 03_MODEL.ipynb ---
def gen_model():
    cells = [
        {"cell_type": "markdown", "metadata": {}, "source": ["# 03. Model Training\n", "Training LSTM and other variants based on experiment mode."]},
        get_experiment_config_cell("Model Training"),
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import torch.nn as nn\n",
                "from torch.utils.data import Dataset, DataLoader\n",
                "from torch.nn.utils.rnn import pad_sequence\n",
                "from sklearn.model_selection import KFold\n",
                "import time\n",
                "\n",
                "DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
                "print(f'Using device: {DEVICE}')\n",
                "\n",
                "# --- Dataset & Models ---\n",
                "\n",
                "class ChordDataset(Dataset):\n",
                "    def __init__(self, sequences):\n",
                "        self.X = [torch.from_numpy(s['X']) for s in sequences]\n",
                "        self.y = [torch.from_numpy(s['y']) for s in sequences]\n",
                "    def __len__(self): return len(self.X)\n",
                "    def __getitem__(self, idx): return self.X[idx], self.y[idx]\n",
                "\n",
                "def collate_fn(batch):\n",
                "    xs, ys = zip(*batch)\n",
                "    lengths = torch.tensor([x.size(0) for x in xs])\n",
                "    x_pad = pad_sequence(xs, batch_first=True, padding_value=0)\n",
                "    y_pad = pad_sequence(ys, batch_first=True, padding_value=-100)\n",
                "    return x_pad, y_pad, lengths\n",
                "\n",
                "class RNNModel(nn.Module):\n",
                "    def __init__(self, input_dim, hidden_dim, output_dim, num_layers=2, dropout=0.3):\n",
                "        super().__init__()\n",
                "        self.rnn = nn.RNN(input_dim, hidden_dim, num_layers, batch_first=True, dropout=dropout)\n",
                "        self.fc = nn.Linear(hidden_dim, output_dim)\n",
                "    def forward(self, x, lengths=None):\n",
                "        out, _ = self.rnn(x)\n",
                "        return self.fc(out)\n",
                "\n",
                "class GRUModel(nn.Module):\n",
                "    def __init__(self, input_dim, hidden_dim, output_dim, num_layers=2, dropout=0.3):\n",
                "        super().__init__()\n",
                "        self.gru = nn.GRU(input_dim, hidden_dim, num_layers, batch_first=True, dropout=dropout)\n",
                "        self.fc = nn.Linear(hidden_dim, output_dim)\n",
                "    def forward(self, x, lengths=None):\n",
                "        out, _ = self.gru(x)\n",
                "        return self.fc(out)\n",
                "\n",
                "class LSTMModel(nn.Module):\n",
                "    def __init__(self, input_dim, hidden_dim, output_dim, num_layers=2, dropout=0.3):\n",
                "        super().__init__()\n",
                "        self.lstm = nn.LSTM(input_dim, hidden_dim, num_layers, batch_first=True, dropout=dropout)\n",
                "        self.fc = nn.Linear(hidden_dim, output_dim)\n",
                "    def forward(self, x, lengths=None):\n",
                "        out, _ = self.lstm(x)\n",
                "        return self.fc(out)\n",
                "\n",
                "class BiLSTMModel(nn.Module):\n",
                "    def __init__(self, input_dim, hidden_dim, output_dim, num_layers=2, dropout=0.3):\n",
                "        super().__init__()\n",
                "        self.lstm = nn.LSTM(input_dim, hidden_dim, num_layers, batch_first=True, dropout=dropout, bidirectional=True)\n",
                "        self.fc = nn.Linear(hidden_dim * 2, output_dim)\n",
                "    def forward(self, x, lengths=None):\n",
                "        out, _ = self.lstm(x)\n",
                "        return self.fc(out)\n",
                "\n",
                "class TransformerModel(nn.Module):\n",
                "    def __init__(self, input_dim, hidden_dim, output_dim, num_layers=2, nhead=4, dropout=0.3):\n",
                "        super().__init__()\n",
                "        self.input_proj = nn.Linear(input_dim, hidden_dim)\n",
                "        encoder_layer = nn.TransformerEncoderLayer(d_model=hidden_dim, nhead=nhead, batch_first=True, dropout=dropout)\n",
                "        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)\n",
                "        self.fc = nn.Linear(hidden_dim, output_dim)\n",
                "    def forward(self, x, lengths=None):\n",
                "        x = self.input_proj(x)\n",
                "        out = self.transformer(x)\n",
                "        return self.fc(out)\n",
                "\n",
                "def get_model(model_key, input_dim, output_dim):\n",
                "    if model_key == 'rnn': return RNNModel(input_dim, 128, output_dim)\n",
                "    if model_key == 'gru': return GRUModel(input_dim, 128, output_dim)\n",
                "    if model_key == 'lstm': return LSTMModel(input_dim, 128, output_dim)\n",
                "    if model_key == 'bilstm': return BiLSTMModel(input_dim, 128, output_dim)\n",
                "    if model_key == 'transformer': return TransformerModel(input_dim, 128, output_dim)\n",
                "    raise ValueError(f'Unknown model: {model_key}')\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def train_model(model, train_loader, val_loader, epochs=50):\n",
                "    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)\n",
                "    criterion = nn.CrossEntropyLoss(ignore_index=-100)\n",
                "    history = {'train_loss': [], 'val_acc': []}\n",
                "    \n",
                "    best_acc = 0\n",
                "    for epoch in range(epochs):\n",
                "        model.train()\n",
                "        t_loss = 0\n",
                "        for xb, yb, lens in train_loader:\n",
                "            xb, yb = xb.to(DEVICE), yb.to(DEVICE)\n",
                "            optimizer.zero_grad()\n",
                "            logits = model(xb)\n",
                "            loss = criterion(logits.view(-1, logits.size(-1)), yb.view(-1))\n",
                "            loss.backward()\n",
                "            optimizer.step()\n",
                "            t_loss += loss.item()\n",
                "        \n",
                "        model.eval()\n",
                "        correct, total = 0, 0\n",
                "        with torch.no_grad():\n",
                "            for xb, yb, lens in val_loader:\n",
                "                xb, yb = xb.to(DEVICE), yb.to(DEVICE)\n",
                "                logits = model(xb)\n",
                "                preds = logits.argmax(dim=-1)\n",
                "                mask = yb != -100\n",
                "                correct += (preds[mask] == yb[mask]).sum().item()\n",
                "                total += mask.sum().item()\n",
                "        \n",
                "        acc = correct / total if total > 0 else 0\n",
                "        history['train_loss'].append(t_loss/len(train_loader))\n",
                "        history['val_acc'].append(acc)\n",
                "        if acc > best_acc: best_acc = acc\n",
                "        if (epoch+1) % 10 == 0: print(f'Epoch {epoch+1}: Loss {t_loss/len(train_loader):.4f}, Acc {acc:.4f}')\n",
                "    \n",
                "    return history, best_acc\n",
                "\n",
                "# --- MAIN TRAINING LOOP ---\n",
                "processed_file = PROCESSED_PATH / 'master_processed_data.pkl'\n",
                "if not processed_file.exists():\n",
                "    raise FileNotFoundError(f'{processed_file} not found. Run preprocessing notebook first.')\n",
                "    \n",
                "with open(processed_file, 'rb') as f:\n",
                "    data_dict = pickle.load(f)\n",
                "\n",
                "results = []\n",
                "for inst in INSTRUMENTS_TO_TEST:\n",
                "    for feat in FEATURES_TO_TEST:\n",
                "        for model_key in MODELS_TO_TEST:\n",
                "            key = f'{inst}_{feat}'\n",
                "            if key not in data_dict: \n",
                "                print(f'Skipping {key} (not in processed data)')\n",
                "                continue\n",
                "            \n",
                "            print(f'\\n>>> Training {model_key.upper()} on {inst.upper()} with {feat.upper()} features...')\n",
                "            entry = data_dict[key]\n",
                "            seqs = entry['sequences']\n",
                "            \n",
                "            # 5-Fold Cross Validation\n",
                "            kf = KFold(n_splits=5, shuffle=True, random_state=RANDOM_SEED)\n",
                "            fold_accs = []\n",
                "            for fold, (train_idx, val_idx) in enumerate(kf.split(seqs)):\n",
                "                print(f'  --- Fold {fold+1}/5 ---')\n",
                "                train_seqs = [seqs[i] for i in train_idx]\n",
                "                val_seqs = [seqs[i] for i in val_idx]\n",
                "                train_ds = ChordDataset(train_seqs)\n",
                "                val_ds = ChordDataset(val_seqs)\n",
                "                \n",
                "                train_loader = DataLoader(train_ds, batch_size=8, shuffle=True, collate_fn=collate_fn)\n",
                "                val_loader = DataLoader(val_ds, batch_size=8, shuffle=False, collate_fn=collate_fn)\n",
                "                \n",
                "                model = get_model(model_key, len(entry['feat_cols']), len(entry['classes'])).to(DEVICE)\n",
                "                hist, best_acc = train_model(model, train_loader, val_loader, epochs=50)\n",
                "                fold_accs.append(best_acc)\n",
                "            \n",
                "            mean_acc = np.mean(fold_accs)\n",
                "            std_acc = np.std(fold_accs)\n",
                "            print(f'  --> CV Mean Acc: {mean_acc:.4f} ± {std_acc:.4f}')\n",
                "            \n",
                "            results.append({\n",
                "                'instrument': inst, 'feature': feat, 'model': model_key, \n",
                "                'best_acc': mean_acc, 'std_acc': std_acc, 'fold_accs': fold_accs\n",
                "            })\n",
                "\n",
                "with open(OUTPUT_PATH / f'results_{EXPERIMENT_MODE.lower()}.json', 'w') as f:\n",
                "    json.dump(results, f)\n",
                "print('\\nAll training sessions complete.')"
            ]
        }
    ]
    create_notebook('03_model.ipynb', cells)

# --- 04_ANALYSIS.ipynb ---
def gen_analysis():
    cells = [
        {"cell_type": "markdown", "metadata": {}, "source": ["# 04. Results Analysis\n", "Visualizing performance and comparisons."]},
        get_experiment_config_cell("Analysis"),
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "results_file = OUTPUT_PATH / f'results_{EXPERIMENT_MODE.lower()}.json'\n",
                "with open(results_file, 'r') as f:\n",
                "    results = json.load(f)\n",
                "\n",
                "rdf = pd.DataFrame(results)\n",
                "\n",
                "if EXPERIMENT_MODE == 'FEATURE_COMPARISON':\n",
                "    plt.figure(figsize=(10, 6))\n",
                "    sns.barplot(data=rdf, x='feature', y='best_acc')\n",
                "    plt.title('Feature Extraction Comparison (LSTM on raw_audio)')\n",
                "    plt.show()\n",
                "elif EXPERIMENT_MODE == 'MODEL_COMPARISON':\n",
                "    plt.figure(figsize=(10, 6))\n",
                "    sns.barplot(data=rdf, x='model', y='best_acc')\n",
                "    plt.title('Model Architecture Comparison (Best Feature on raw_audio)')\n",
                "    plt.show()\n",
                "elif EXPERIMENT_MODE == 'INSTRUMENT_COMPARISON':\n",
                "    plt.figure(figsize=(12, 6))\n",
                "    sns.barplot(data=rdf, x='instrument', y='best_acc')\n",
                "    plt.title('Instrument Comparison (Best Model + Best Feature)')\n",
                "    plt.xticks(rotation=45)\n",
                "    plt.show()"
            ]
        }
    ]
    create_notebook('04_analysis.ipynb', cells)

if __name__ == '__main__':
    gen_eda()
    gen_preprocessing()
    gen_model()
    gen_analysis()
